# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bank.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 536)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 771, 501))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 501))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 0, 811, 461))
        self.widget.setObjectName("widget")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(370, 10, 431, 441))
        self.widget_3.setObjectName("widget_3")
        self.treeWidget = QtWidgets.QTreeWidget(self.widget_3)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 371, 421))
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.headerItem().setFont(2, font)
        self.widget_1 = QtWidgets.QWidget(self.widget)
        self.widget_1.setGeometry(QtCore.QRect(10, 10, 331, 361))
        self.widget_1.setObjectName("widget_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_1.setGeometry(QtCore.QRect(120, 10, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_4 = QtWidgets.QLabel(self.widget_1)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_1)
        self.label_5.setGeometry(QtCore.QRect(30, 70, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_1)
        self.label_6.setGeometry(QtCore.QRect(30, 130, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 70, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 130, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_1)
        self.pushButton_9.setGeometry(QtCore.QRect(250, 320, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget_1)
        self.comboBox_5.setGeometry(QtCore.QRect(120, 140, 51, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(10, 380, 331, 71))
        self.widget_2.setObjectName("widget_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 390, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setGeometry(QtCore.QRect(160, 510, 341, 71))
        self.widget_4.setObjectName("widget_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_6.setGeometry(QtCore.QRect(90, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_8.setGeometry(QtCore.QRect(260, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.widget_5 = QtWidgets.QWidget(self.tab_2)
        self.widget_5.setGeometry(QtCore.QRect(10, 0, 811, 461))
        self.widget_5.setObjectName("widget_5")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setGeometry(QtCore.QRect(370, 10, 431, 441))
        self.widget_6.setObjectName("widget_6")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.widget_6)
        self.treeWidget_2.setGeometry(QtCore.QRect(10, 10, 371, 421))
        self.treeWidget_2.setObjectName("treeWidget_2")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.headerItem().setFont(2, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.headerItem().setFont(3, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.headerItem().setFont(4, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.headerItem().setFont(5, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_2.headerItem().setFont(6, font)
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setGeometry(QtCore.QRect(10, 10, 331, 361))
        self.widget_7.setObjectName("widget_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 10, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_7)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 110, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_10.setGeometry(QtCore.QRect(250, 320, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_9 = QtWidgets.QLabel(self.widget_7)
        self.label_9.setGeometry(QtCore.QRect(20, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_7)
        self.label_10.setGeometry(QtCore.QRect(20, 170, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 170, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_11 = QtWidgets.QLabel(self.widget_7)
        self.label_11.setGeometry(QtCore.QRect(20, 230, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_7.setGeometry(QtCore.QRect(120, 230, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.dateEdit = QtWidgets.QDateEdit(self.widget_7)
        self.dateEdit.setGeometry(QtCore.QRect(210, 290, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_12 = QtWidgets.QLabel(self.widget_7)
        self.label_12.setGeometry(QtCore.QRect(20, 280, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_3.setGeometry(QtCore.QRect(120, 290, 51, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_22.setGeometry(QtCore.QRect(120, 60, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setGeometry(QtCore.QRect(10, 380, 331, 71))
        self.widget_8.setObjectName("widget_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_12.setGeometry(QtCore.QRect(90, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_13.setGeometry(QtCore.QRect(170, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_14.setGeometry(QtCore.QRect(260, 390, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget_9 = QtWidgets.QWidget(self.tab_3)
        self.widget_9.setGeometry(QtCore.QRect(10, 0, 811, 461))
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setGeometry(QtCore.QRect(370, 10, 431, 441))
        self.widget_10.setObjectName("widget_10")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.widget_10)
        self.treeWidget_3.setGeometry(QtCore.QRect(10, 10, 371, 421))
        self.treeWidget_3.setObjectName("treeWidget_3")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_3.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_3.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_3.headerItem().setFont(2, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_3.headerItem().setFont(3, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_3.headerItem().setFont(4, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_3.headerItem().setFont(5, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_3.headerItem().setFont(6, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_3.headerItem().setFont(7, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_3.headerItem().setFont(8, font)
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setGeometry(QtCore.QRect(10, 10, 331, 361))
        self.widget_11.setObjectName("widget_11")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_8.setGeometry(QtCore.QRect(140, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_13 = QtWidgets.QLabel(self.widget_11)
        self.label_13.setGeometry(QtCore.QRect(10, 0, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_9.setGeometry(QtCore.QRect(140, 90, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_15.setGeometry(QtCore.QRect(250, 330, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_15 = QtWidgets.QLabel(self.widget_11)
        self.label_15.setGeometry(QtCore.QRect(10, 80, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.widget_11)
        self.label_16.setGeometry(QtCore.QRect(10, 120, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_10.setGeometry(QtCore.QRect(140, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_17 = QtWidgets.QLabel(self.widget_11)
        self.label_17.setGeometry(QtCore.QRect(10, 160, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_11.setGeometry(QtCore.QRect(140, 170, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_18 = QtWidgets.QLabel(self.widget_11)
        self.label_18.setGeometry(QtCore.QRect(10, 200, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_12.setGeometry(QtCore.QRect(140, 210, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_19 = QtWidgets.QLabel(self.widget_11)
        self.label_19.setGeometry(QtCore.QRect(10, 240, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_13.setGeometry(QtCore.QRect(140, 250, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_20 = QtWidgets.QLabel(self.widget_11)
        self.label_20.setGeometry(QtCore.QRect(10, 280, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_14.setGeometry(QtCore.QRect(140, 290, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_21 = QtWidgets.QLabel(self.widget_11)
        self.label_21.setGeometry(QtCore.QRect(10, 320, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_15.setGeometry(QtCore.QRect(140, 330, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_22 = QtWidgets.QLabel(self.widget_11)
        self.label_22.setGeometry(QtCore.QRect(10, 40, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_16.setGeometry(QtCore.QRect(160, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.widget_12 = QtWidgets.QWidget(self.widget_9)
        self.widget_12.setGeometry(QtCore.QRect(10, 380, 331, 71))
        self.widget_12.setObjectName("widget_12")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_17.setGeometry(QtCore.QRect(90, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_18.setGeometry(QtCore.QRect(170, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_19.setGeometry(QtCore.QRect(260, 390, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_13 = QtWidgets.QWidget(self.tab_4)
        self.widget_13.setGeometry(QtCore.QRect(10, 0, 811, 461))
        self.widget_13.setObjectName("widget_13")
        self.widget_14 = QtWidgets.QWidget(self.widget_13)
        self.widget_14.setGeometry(QtCore.QRect(370, 10, 431, 441))
        self.widget_14.setObjectName("widget_14")
        self.treeWidget_4 = QtWidgets.QTreeWidget(self.widget_14)
        self.treeWidget_4.setGeometry(QtCore.QRect(10, 10, 371, 421))
        self.treeWidget_4.setObjectName("treeWidget_4")
        self.widget_15 = QtWidgets.QWidget(self.widget_13)
        self.widget_15.setGeometry(QtCore.QRect(10, 10, 331, 361))
        self.widget_15.setObjectName("widget_15")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.widget_15)
        self.lineEdit_17.setGeometry(QtCore.QRect(130, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_14 = QtWidgets.QLabel(self.widget_15)
        self.label_14.setGeometry(QtCore.QRect(30, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_23 = QtWidgets.QLabel(self.widget_15)
        self.label_23.setGeometry(QtCore.QRect(30, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_15)
        self.label_24.setGeometry(QtCore.QRect(30, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.widget_15)
        self.lineEdit_19.setGeometry(QtCore.QRect(200, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.widget_15)
        self.pushButton_20.setGeometry(QtCore.QRect(250, 320, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.widget_15)
        self.dateEdit_2.setGeometry(QtCore.QRect(210, 70, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 70, 51, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_4.setGeometry(QtCore.QRect(130, 120, 51, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget_15)
        self.lineEdit_25.setGeometry(QtCore.QRect(140, 200, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_31 = QtWidgets.QLabel(self.widget_15)
        self.label_31.setGeometry(QtCore.QRect(80, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.widget_15)
        self.label_32.setGeometry(QtCore.QRect(50, 240, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.widget_15)
        self.lineEdit_26.setGeometry(QtCore.QRect(140, 240, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.widget_15)
        self.lineEdit_27.setGeometry(QtCore.QRect(140, 280, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_33 = QtWidgets.QLabel(self.widget_15)
        self.label_33.setGeometry(QtCore.QRect(70, 280, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.widget_15)
        self.label_34.setGeometry(QtCore.QRect(30, 160, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.comboBox_7 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_7.setGeometry(QtCore.QRect(140, 160, 101, 31))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.widget_16 = QtWidgets.QWidget(self.widget_13)
        self.widget_16.setGeometry(QtCore.QRect(10, 380, 331, 71))
        self.widget_16.setObjectName("widget_16")
        self.pushButton_21 = QtWidgets.QPushButton(self.widget_16)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.widget_16)
        self.pushButton_22.setGeometry(QtCore.QRect(90, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.widget_16)
        self.pushButton_23.setGeometry(QtCore.QRect(170, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_24.setGeometry(QtCore.QRect(260, 390, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_17 = QtWidgets.QWidget(self.tab_5)
        self.widget_17.setGeometry(QtCore.QRect(10, 0, 811, 461))
        self.widget_17.setObjectName("widget_17")
        self.widget_18 = QtWidgets.QWidget(self.widget_17)
        self.widget_18.setGeometry(QtCore.QRect(370, 10, 431, 441))
        self.widget_18.setObjectName("widget_18")
        self.treeWidget_5 = QtWidgets.QTreeWidget(self.widget_18)
        self.treeWidget_5.setGeometry(QtCore.QRect(10, 10, 371, 421))
        self.treeWidget_5.setObjectName("treeWidget_5")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_5.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_5.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_5.headerItem().setFont(2, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_5.headerItem().setFont(3, font)
        self.widget_19 = QtWidgets.QWidget(self.widget_17)
        self.widget_19.setGeometry(QtCore.QRect(10, 10, 331, 361))
        self.widget_19.setObjectName("widget_19")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.widget_19)
        self.lineEdit_18.setGeometry(QtCore.QRect(200, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_25 = QtWidgets.QLabel(self.widget_19)
        self.label_25.setGeometry(QtCore.QRect(30, 70, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_27 = QtWidgets.QLabel(self.widget_19)
        self.label_27.setGeometry(QtCore.QRect(30, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget_19)
        self.lineEdit_20.setGeometry(QtCore.QRect(130, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.pushButton_25 = QtWidgets.QPushButton(self.widget_19)
        self.pushButton_25.setGeometry(QtCore.QRect(250, 170, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.label_28 = QtWidgets.QLabel(self.widget_19)
        self.label_28.setGeometry(QtCore.QRect(30, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.widget_19)
        self.lineEdit_21.setGeometry(QtCore.QRect(130, 130, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.comboBox_6 = QtWidgets.QComboBox(self.widget_19)
        self.comboBox_6.setGeometry(QtCore.QRect(130, 80, 51, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.widget_19)
        self.lineEdit_23.setGeometry(QtCore.QRect(140, 220, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.pushButton_30 = QtWidgets.QPushButton(self.widget_19)
        self.pushButton_30.setGeometry(QtCore.QRect(250, 310, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName("pushButton_30")
        self.label_29 = QtWidgets.QLabel(self.widget_19)
        self.label_29.setGeometry(QtCore.QRect(30, 220, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget_19)
        self.lineEdit_24.setGeometry(QtCore.QRect(140, 270, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_30 = QtWidgets.QLabel(self.widget_19)
        self.label_30.setGeometry(QtCore.QRect(30, 270, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.widget_20 = QtWidgets.QWidget(self.widget_17)
        self.widget_20.setGeometry(QtCore.QRect(10, 380, 331, 71))
        self.widget_20.setObjectName("widget_20")
        self.pushButton_26 = QtWidgets.QPushButton(self.widget_20)
        self.pushButton_26.setGeometry(QtCore.QRect(10, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.widget_20)
        self.pushButton_27.setGeometry(QtCore.QRect(90, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.widget_20)
        self.pushButton_28.setGeometry(QtCore.QRect(170, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.widget_17)
        self.pushButton_29.setGeometry(QtCore.QRect(260, 390, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.widget_21 = QtWidgets.QWidget(self.tab_6)
        self.widget_21.setGeometry(QtCore.QRect(10, 10, 741, 211))
        self.widget_21.setObjectName("widget_21")
        self.pushButton_32 = QtWidgets.QPushButton(self.widget_21)
        self.pushButton_32.setGeometry(QtCore.QRect(10, 150, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setObjectName("pushButton_32")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.widget_21)
        self.dateEdit_3.setGeometry(QtCore.QRect(10, 70, 110, 22))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.pushButton_35 = QtWidgets.QPushButton(self.widget_21)
        self.pushButton_35.setGeometry(QtCore.QRect(220, 150, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setObjectName("pushButton_35")
        self.dateEdit_4 = QtWidgets.QDateEdit(self.widget_21)
        self.dateEdit_4.setGeometry(QtCore.QRect(180, 70, 110, 22))
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.label = QtWidgets.QLabel(self.widget_21)
        self.label.setGeometry(QtCore.QRect(140, 70, 21, 16))
        self.label.setObjectName("label")
        self.treeWidget_6 = QtWidgets.QTreeWidget(self.widget_21)
        self.treeWidget_6.setGeometry(QtCore.QRect(310, 10, 411, 191))
        self.treeWidget_6.setObjectName("treeWidget_6")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_6.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_6.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_6.headerItem().setFont(2, font)
        self.label_3 = QtWidgets.QLabel(self.widget_21)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget_22 = QtWidgets.QWidget(self.tab_6)
        self.widget_22.setGeometry(QtCore.QRect(10, 230, 741, 211))
        self.widget_22.setObjectName("widget_22")
        self.pushButton_34 = QtWidgets.QPushButton(self.widget_22)
        self.pushButton_34.setGeometry(QtCore.QRect(10, 150, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setObjectName("pushButton_34")
        self.dateEdit_6 = QtWidgets.QDateEdit(self.widget_22)
        self.dateEdit_6.setGeometry(QtCore.QRect(10, 70, 110, 22))
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.pushButton_36 = QtWidgets.QPushButton(self.widget_22)
        self.pushButton_36.setGeometry(QtCore.QRect(220, 150, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setObjectName("pushButton_36")
        self.dateEdit_7 = QtWidgets.QDateEdit(self.widget_22)
        self.dateEdit_7.setGeometry(QtCore.QRect(180, 70, 110, 22))
        self.dateEdit_7.setObjectName("dateEdit_7")
        self.label_2 = QtWidgets.QLabel(self.widget_22)
        self.label_2.setGeometry(QtCore.QRect(140, 70, 21, 16))
        self.label_2.setObjectName("label_2")
        self.treeWidget_7 = QtWidgets.QTreeWidget(self.widget_22)
        self.treeWidget_7.setGeometry(QtCore.QRect(310, 10, 411, 191))
        self.treeWidget_7.setObjectName("treeWidget_7")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_7.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_7.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget_7.headerItem().setFont(2, font)
        self.label_26 = QtWidgets.QLabel(self.widget_22)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "城市"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "支行名"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "资产"))
        self.label_4.setText(_translate("MainWindow", "城市："))
        self.label_5.setText(_translate("MainWindow", "名字："))
        self.label_6.setText(_translate("MainWindow", "资产："))
        self.pushButton_9.setText(_translate("MainWindow", "清空"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "="))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "!="))
        self.comboBox_5.setItemText(2, _translate("MainWindow", ">"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "<"))
        self.pushButton.setText(_translate("MainWindow", "增"))
        self.pushButton_2.setText(_translate("MainWindow", "删"))
        self.pushButton_3.setText(_translate("MainWindow", "改"))
        self.pushButton_4.setText(_translate("MainWindow", "查"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "支行管理"))
        self.pushButton_5.setText(_translate("MainWindow", "增"))
        self.pushButton_6.setText(_translate("MainWindow", "删"))
        self.pushButton_7.setText(_translate("MainWindow", "改"))
        self.pushButton_8.setText(_translate("MainWindow", "查"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "身份证号"))
        self.treeWidget_2.headerItem().setText(1, _translate("MainWindow", "是否经理"))
        self.treeWidget_2.headerItem().setText(2, _translate("MainWindow", "经理身份证号"))
        self.treeWidget_2.headerItem().setText(3, _translate("MainWindow", "姓名"))
        self.treeWidget_2.headerItem().setText(4, _translate("MainWindow", "电话号码"))
        self.treeWidget_2.headerItem().setText(5, _translate("MainWindow", "家庭住址"))
        self.treeWidget_2.headerItem().setText(6, _translate("MainWindow", "工作日期"))
        self.label_7.setText(_translate("MainWindow", "身份证号："))
        self.label_8.setText(_translate("MainWindow", "经理身份证："))
        self.pushButton_10.setText(_translate("MainWindow", "清空"))
        self.label_9.setText(_translate("MainWindow", "姓名："))
        self.label_10.setText(_translate("MainWindow", "电话号码："))
        self.label_11.setText(_translate("MainWindow", "家庭住址："))
        self.label_12.setText(_translate("MainWindow", "开始日期："))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "="))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "!="))
        self.comboBox_3.setItemText(2, _translate("MainWindow", ">"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "<"))
        self.pushButton_11.setText(_translate("MainWindow", "增"))
        self.pushButton_12.setText(_translate("MainWindow", "删"))
        self.pushButton_13.setText(_translate("MainWindow", "改"))
        self.pushButton_14.setText(_translate("MainWindow", "查"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "员工管理"))
        self.treeWidget_3.headerItem().setText(0, _translate("MainWindow", "身份证号"))
        self.treeWidget_3.headerItem().setText(1, _translate("MainWindow", "管理人身份证"))
        self.treeWidget_3.headerItem().setText(2, _translate("MainWindow", "姓名"))
        self.treeWidget_3.headerItem().setText(3, _translate("MainWindow", "联系电话"))
        self.treeWidget_3.headerItem().setText(4, _translate("MainWindow", "家庭住址"))
        self.treeWidget_3.headerItem().setText(5, _translate("MainWindow", "联系人姓名"))
        self.treeWidget_3.headerItem().setText(6, _translate("MainWindow", "联系人手机号"))
        self.treeWidget_3.headerItem().setText(7, _translate("MainWindow", "联系人Email"))
        self.treeWidget_3.headerItem().setText(8, _translate("MainWindow", "联系人关系"))
        self.label_13.setText(_translate("MainWindow", "身份证号："))
        self.pushButton_15.setText(_translate("MainWindow", "清空"))
        self.label_15.setText(_translate("MainWindow", "姓名："))
        self.label_16.setText(_translate("MainWindow", "联系电话："))
        self.label_17.setText(_translate("MainWindow", "家庭住址："))
        self.label_18.setText(_translate("MainWindow", "联系人姓名："))
        self.label_19.setText(_translate("MainWindow", "联系人手机号："))
        self.label_20.setText(_translate("MainWindow", "联系人Email："))
        self.label_21.setText(_translate("MainWindow", "联系人关系："))
        self.label_22.setText(_translate("MainWindow", "管理人身份证："))
        self.pushButton_16.setText(_translate("MainWindow", "增"))
        self.pushButton_17.setText(_translate("MainWindow", "删"))
        self.pushButton_18.setText(_translate("MainWindow", "改"))
        self.pushButton_19.setText(_translate("MainWindow", "查"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "客户管理"))
        self.label_14.setText(_translate("MainWindow", "账户号："))
        self.label_23.setText(_translate("MainWindow", "开户日期："))
        self.label_24.setText(_translate("MainWindow", "余额："))
        self.pushButton_20.setText(_translate("MainWindow", "清空"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "="))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "!="))
        self.comboBox_2.setItemText(2, _translate("MainWindow", ">"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "<"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "="))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "!="))
        self.comboBox_4.setItemText(2, _translate("MainWindow", ">"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "<"))
        self.label_31.setText(_translate("MainWindow", "利率："))
        self.label_32.setText(_translate("MainWindow", "货币类型："))
        self.label_33.setText(_translate("MainWindow", "透支额："))
        self.label_34.setText(_translate("MainWindow", "账户类型："))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "储蓄"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "贷款"))
        self.pushButton_21.setText(_translate("MainWindow", "增"))
        self.pushButton_22.setText(_translate("MainWindow", "删"))
        self.pushButton_23.setText(_translate("MainWindow", "改"))
        self.pushButton_24.setText(_translate("MainWindow", "查"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "账户管理"))
        self.treeWidget_5.headerItem().setText(0, _translate("MainWindow", "贷款号"))
        self.treeWidget_5.headerItem().setText(1, _translate("MainWindow", "金额"))
        self.treeWidget_5.headerItem().setText(2, _translate("MainWindow", "名字"))
        self.treeWidget_5.headerItem().setText(3, _translate("MainWindow", "发放状态"))
        self.label_25.setText(_translate("MainWindow", "金额："))
        self.label_27.setText(_translate("MainWindow", "贷款号："))
        self.pushButton_25.setText(_translate("MainWindow", "清空"))
        self.label_28.setText(_translate("MainWindow", "名字："))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "="))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "!="))
        self.comboBox_6.setItemText(2, _translate("MainWindow", ">"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "<"))
        self.pushButton_30.setText(_translate("MainWindow", "发放"))
        self.label_29.setText(_translate("MainWindow", "发放金额："))
        self.label_30.setText(_translate("MainWindow", "身份证号："))
        self.pushButton_26.setText(_translate("MainWindow", "增"))
        self.pushButton_27.setText(_translate("MainWindow", "删"))
        self.pushButton_28.setText(_translate("MainWindow", "改"))
        self.pushButton_29.setText(_translate("MainWindow", "查"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "贷款管理"))
        self.pushButton_32.setText(_translate("MainWindow", "储蓄统计"))
        self.pushButton_35.setText(_translate("MainWindow", "清空"))
        self.label.setText(_translate("MainWindow", "to"))
        self.treeWidget_6.headerItem().setText(0, _translate("MainWindow", "支行名"))
        self.treeWidget_6.headerItem().setText(1, _translate("MainWindow", "客户数"))
        self.treeWidget_6.headerItem().setText(2, _translate("MainWindow", "总金额"))
        self.label_3.setText(_translate("MainWindow", "区间设置："))
        self.pushButton_34.setText(_translate("MainWindow", "贷款统计"))
        self.pushButton_36.setText(_translate("MainWindow", "清空"))
        self.label_2.setText(_translate("MainWindow", "to"))
        self.treeWidget_7.headerItem().setText(0, _translate("MainWindow", "支行名"))
        self.treeWidget_7.headerItem().setText(1, _translate("MainWindow", "用户数"))
        self.treeWidget_7.headerItem().setText(2, _translate("MainWindow", "总金额"))
        self.label_26.setText(_translate("MainWindow", "区间设置："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "统计查询"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

